cat > .github/workflows/test_api.yml << EOL
name: Test OpenAI API

on: [push]

jobs:
  test_api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openai
    - name: Run API test
      env:
        OPENAI_API_KEY: \${{ secrets.OPENAI_API_KEY }}
      run: python test_api.py
EOL
